---
title: "Visualziation"
author: "Jingzhi Kevin Yu"
date: "1/20/2022"
output: html_document
---

```{r setup, include=FALSE}
if (!require(tidyverse)) install.packages('tidyverse')

library(ggplot2)
library(tidyverse)
library("viridis") 
library(nricens)
library(caret)
library(pROC)

df = read_csv('/Users/excenity/Documents/HSIP/Research/Longitudinal PCE/GitHub/Dynamic-DeepHit LRPP/AUC + Risk Calculations/risk_df_order.csv')

df$risk_cat_pce = factor(df$risk_cat_pce, levels = c('Low Risk', 'Borderline Risk', 'Intermediate Risk', 'High Risk'))
```

```{r, fig.width = 8, fig.height= 6}
ggplot(df, aes(x = risk_order_pce, y = risk_order_ddh, color = risk_cat_pce)) + geom_point(alpha = .75) + theme_bw() + geom_abline(color = 'green', linewidth = 1.55) + scale_color_viridis(discrete = T, option = 'C', direction = -1)
```

```{r, fig.width = 8, fig.height= 6}
df$true_label = as.factor(df$true_label)
df %>% group_by(risk_cat_pce) %>% summarise_at(vars(risk_order_pce), min)
ggplot(df, aes(x = risk_order_pce, y = risk_order_ddh, color = true_label)) + geom_point(alpha = .5) + theme_bw() + geom_abline(color = 'red') + scale_discrete_manual(values=c('gray', 'red'), aesthetics = 'colour') + geom_vline(xintercept = 1274, color = 'green', linetype = 'dashed') + geom_vline(xintercept = 1642, color = 'yellow', linetype = 'dashed') + geom_vline(xintercept = 2382, color = 'red', linetype = 'dashed') + xlab('PCE Risk Rank') + ylab('DDH Risk Rank')
```

AUC CIs
```{r}
# PCE
auc(df$true_label, df$risk)
ci.auc(df$true_label, df$risk)

# DDH
auc(df$true_label, df$value)
ci.auc(df$true_label, df$value)
```

Continuous NRI 
Formula: [(up - down)/(up + down + unchanged) in Y = 1] - [(up - down)/(up + down + unchanged) in Y = 0]
```{r}
df$value = round(df$value, 3)

# categorize
df$reclassification = 0 #down
df$reclassification[df$risk < df$value] = 1 #up
df$reclassification[df$risk == df$value] = 2 #unchanged

table(df$true_label, df$reclassification)

down_1 = df %>% filter(reclassification ==0 & true_label == 1) %>% count()
up_1 = df %>% filter(reclassification == 1 & true_label == 1) %>% count()
unchanged_1 = df %>% filter(reclassification == 2 & true_label == 1) %>% count()

down_0 = df %>% filter(reclassification ==0 & true_label == 0) %>% count()
up_0 = df %>% filter(reclassification == 1 & true_label == 0) %>% count()
unchanged_0 = df %>% filter(reclassification == 2 & true_label == 0) %>% count()

((up_1 - down_1)/(up_1 + down_1 + unchanged_1)) - ((up_0 - down_0)/(down_0 + up_0 + unchanged_0))
```

Risk Visualization
```{r, fig.height = 5, fig.width = 5}
# ddh
df$risk_deciles_ddh = ntile(df$risk_order_ddh, 10)
df$true_label = as.numeric(as.character(df$true_label))
decile_comp = df %>% group_by(risk_deciles_ddh) %>% summarise_at(vars(value, true_label), mean)
decile_comp
names(decile_comp) = c('risk_deciles_ddh', 'mean_risk', 'obs_risk')

ggplot(decile_comp, aes(x = mean_risk, y = obs_risk)) + geom_point() + xlim(0, 0.25) + ylim(0, 0.25) +coord_fixed() + geom_abline(color = 'red') + xlab('Predicted Risk') + ylab('Observed Risk') + ggtitle('DDH - Risk Comparison') + theme_bw()

# pce
df$risk_deciles_pce = ntile(df$risk_order_pce, 10)
df$true_label = as.numeric(as.character(df$true_label))
decile_comp = df %>% group_by(risk_deciles_pce) %>% summarise_at(vars(risk, true_label), mean)
head(decile_comp)
names(decile_comp) = c('risk_deciles_pce', 'mean_risk', 'obs_risk')

ggplot(decile_comp, aes(x = mean_risk, y = obs_risk)) + geom_point() + xlim(0, 0.25) + ylim(0, 0.25) +coord_fixed() + geom_abline(color = 'red') + xlab('Predicted Risk') + ylab('Observed Risk') + ggtitle('PCE - Risk Comparision') + theme_bw()
```


NRI
```{r, fig.width = 6, fig.height = 4}
NRI_calc = function(pce_threshold)
{
  df$pce_pred = ifelse(df$risk >= pce_threshold, 1, 0)
  pce_low_risk_n = df %>% filter(pce_pred == 0) %>% count()
  pce_low_risk_n = pce_low_risk_n$n
  pce_high_risk_n = df %>% filter(pce_pred == 1) %>% count()
  pce_high_risk_n = pce_high_risk_n$n
  
  NRI_list = c()
  thresholds = seq(from = 0, to = 0.125, by = 0.005)
  
  for (i in thresholds)
  {
    #label correct predictions
    df$ddh_pred = ifelse(df$value >= i, 1, 0)
    df$matched = 0
    df$matched[df$true_label == df$ddh_pred] = 1
    
    #NRIevents (high risk)
    ddh_correct_event = df %>% filter(true_label == 1 & matched == 1 & pce_pred != ddh_pred) %>% count()
    ddh_incorrect_event = df %>% filter(true_label == 1 & matched == 0 & pce_pred != ddh_pred) %>% count()
    NRI_e = (ddh_correct_event - ddh_incorrect_event) / pce_high_risk_n
    
    #NRIevents (high risk)
    ddh_correct_nonevent = df %>% filter(true_label == 0 & matched == 1 & pce_pred != ddh_pred) %>% count()
    ddh_incorrect_nonevent = df %>% filter(true_label == 0 & matched == 0 & pce_pred != ddh_pred) %>% count()
    NRI_ne = (ddh_correct_nonevent - ddh_incorrect_nonevent) / pce_low_risk_n
    
    NRI = NRI_e + NRI_ne
    
    NRI_list = c(NRI_list, NRI)
  }
  
  NRI_list = as.data.frame(NRI_list)
  NRI_list = as.data.frame(t(NRI_list))
  NRI_list$threshold = thresholds
  
  names(NRI_list) = c('NRI', 'Threshold')
  print(ggplot(NRI_list, aes(x = Threshold, y = NRI)) + geom_line() + geom_hline(yintercept = 0, color = 'red') + theme_bw() + ggtitle(paste0('NRI ', '(PCE Threshold = ', pce_threshold,')')))
  
  return(NRI_list)
}

NRI_list_0075 = NRI_calc(0.075)
NRI_list_01 = NRI_calc(0.1)
NRI_list_01 = NRI_calc(0.2)
```

Brier Score
```{r}
# PCE
brier_score = df 
brier_score$true_label = as.numeric(brier_score$true_label) - 1
brier_score$bs_diff = brier_score$risk - brier_score$true_label
sum(brier_score$bs_diff)^2/nrow(brier_score)

# DDH
brier_score = df 
brier_score$true_label = as.numeric(brier_score$true_label) - 1
brier_score$bs_diff = brier_score$value - brier_score$true_label
sum(brier_score$bs_diff)^2/nrow(brier_score)
```

```{r, fig.width = 8, fig.height= 6}
ggplot(df, aes(x = log(risk), y = value, color = true_label)) + geom_point(alpha = .5, fill = 'white') + theme_bw() + scale_color_manual(values=c('lightgray', 'red')) + xlab('pce_risk(logged)') + ylab('ddh_risk') +
  geom_vline(xintercept = log(0.05), color = 'green', linetype = 'dashed') + geom_vline(xintercept = log(0.075), color = 'gold', linetype = 'dashed') + geom_vline(xintercept = log(0.2), color = 'red', linetype = 'dashed')
```

```{r, fig.width=4, fig.height=4}
# pce roc
roc_score_pce = roc(df$true_label, df$risk)
roc_score_ddh = roc(df$true_label, df$value)
plot.roc(roc_score_pce, main ="PCE", colorize = T, print.auc = T,, col = 'chartreuse3')
plot.roc(roc_score_ddh, main ="DDH", add = T, colorize = T, print.auc = T, col = 'coral2',  print.auc.y = 0.6 )
````
